# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel


class StartAgentsRequestPropertiesParametersSpeak(UncheckedBaseModel):
    """
    Settings for the agent's speak behavior.
    """

    batch: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether to skip sentence segmentation for speak requests:
    - `false`: Skip sentence segmentation.
    - Omitted or `true`: Preserve sentence segmentation.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
