# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from .start_agents_request_properties_filler_words_content_generated_config import (
    StartAgentsRequestPropertiesFillerWordsContentGeneratedConfig,
)
from .start_agents_request_properties_filler_words_content_mode import (
    StartAgentsRequestPropertiesFillerWordsContentMode,
)
from .start_agents_request_properties_filler_words_content_static_config import (
    StartAgentsRequestPropertiesFillerWordsContentStaticConfig,
)


class StartAgentsRequestPropertiesFillerWordsContent(UncheckedBaseModel):
    """
    Filler word content configuration. Defines the source and selection rules for filler words.
    """

    mode: typing.Optional[StartAgentsRequestPropertiesFillerWordsContentMode] = pydantic.Field(default=None)
    """
    Filler word content mode:
    - `static`: Static filler words. Uses a predefined list of filler words.
    - `generated`: LLM-generated filler words based on the last user message.
    """

    static_config: typing.Optional[StartAgentsRequestPropertiesFillerWordsContentStaticConfig] = pydantic.Field(
        default=None
    )
    """
    Static filler word configuration. Required when `mode` is `static`.
    """

    generated_config: typing.Optional[StartAgentsRequestPropertiesFillerWordsContentGeneratedConfig] = pydantic.Field(
        default=None
    )
    """
    Optional configuration for generated filler words. When omitted, the service uses its default generator settings.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
