# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from .start_agents_request_properties_filler_words_content_generated_config_llm_provider import (
    StartAgentsRequestPropertiesFillerWordsContentGeneratedConfigLlmProvider,
)


class StartAgentsRequestPropertiesFillerWordsContentGeneratedConfig(UncheckedBaseModel):
    """
    Optional configuration for generated filler words. When omitted, the service uses its default generator settings.
    """

    llm_provider: typing.Optional[StartAgentsRequestPropertiesFillerWordsContentGeneratedConfigLlmProvider] = (
        pydantic.Field(default=None)
    )
    """
    OpenAI-compatible LLM provider used to generate filler words. Runs in parallel with the main business LLM and only uses the last user message as input.
    """

    prompt: typing.Optional[str] = pydantic.Field(default=None)
    """
    System prompt used to generate a short filler phrase based on the last user message. The generated text should be conversational and must not answer the user's question.
    """

    fallback_strategy: typing.Optional[typing.Literal["static"]] = pydantic.Field(default=None)
    """
    Fallback strategy when generated filler text is not ready, fails, or returns empty text. Phase 1 only supports `static`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
