# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .anam_avatar_params_quality import AnamAvatarParamsQuality
from .anam_avatar_params_video_encoding import AnamAvatarParamsVideoEncoding


class AnamAvatarParams(UncheckedBaseModel):
    """
    Anam Avatar configuration parameters.
    """

    api_key: str = pydantic.Field()
    """
    Anam API key.
    """

    avatar_id: str = pydantic.Field()
    """
    The unique identifier for the Anam avatar you want to use.
    """

    agora_uid: str = pydantic.Field()
    """
    The unique identifier for the avatar's RTC connection. This must be different from other participants in the channel.
    """

    agora_token: str = pydantic.Field()
    """
    The RTC token that authorizes the avatar to join the video channel.
    """

    sample_rate: typing.Optional[int] = pydantic.Field(default=None)
    """
    The audio sample rate in Hz.
    """

    quality: typing.Optional[AnamAvatarParamsQuality] = pydantic.Field(default=None)
    """
    The video quality level.
    """

    video_encoding: typing.Optional[AnamAvatarParamsVideoEncoding] = pydantic.Field(default=None)
    """
    The video encoding format.
    """

    avatar_model: typing.Optional[str] = pydantic.Field(default=None)
    """
    Anam avatar model, such as `cara_mk4` for Cara 4 portrait mode.
    """

    video_width: typing.Optional[int] = pydantic.Field(default=None)
    """
    Anam output video width in pixels. Set together with `video_height`; omit both to use the model default resolution.
    """

    video_height: typing.Optional[int] = pydantic.Field(default=None)
    """
    Anam output video height in pixels. Set together with `video_width`; omit both to use the model default resolution.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
