# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class GeminiAsrParams(UncheckedBaseModel):
    """
    Google Gemini ASR configuration parameters.
    """

    api_key: str = pydantic.Field()
    """
    Google Gemini API key.
    """

    model: str = pydantic.Field()
    """
    Gemini transcription model identifier.
    """

    sample_rate: typing.Optional[int] = pydantic.Field(default=None)
    """
    Audio sample rate in Hz.
    """

    language: typing.Optional[str] = pydantic.Field(default=None)
    """
    Language code for speech recognition.
    """

    word_timestamp: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether to include word-level timestamps in transcription results.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
