# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .llm_tool_execution import LlmToolExecution
from .llm_tool_function import LlmToolFunction
from .llm_tool_server import LlmToolServer


class LlmTool(UncheckedBaseModel):
    """
    Inline REST tool definition. `type: function` combined with `server` declares a REST tool.
    Phase 1a executes the HTTP request synchronously and returns the raw result to the model context.
    """

    type: typing.Literal["function"] = pydantic.Field(default="function")
    """
    Tool type. Must be `function`.
    """

    function: LlmToolFunction = pydantic.Field()
    """
    Tool interface exposed to the model. `parameters` is the JSON Schema for LLM arguments, not the HTTP request shape.
    """

    execution: typing.Optional[LlmToolExecution] = pydantic.Field(default=None)
    """
    Tool execution configuration. Defaults to `{"mode": "sync"}`. Phase 1a only allows `sync`.
    """

    server: LlmToolServer = pydantic.Field()
    """
    Actual HTTP request configuration for this REST tool.
    Does not use top-level `parameters`, `path_params`, standalone `query`,
    `response`, `json_path`, or `max_chars`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
