# This file was auto-generated by Fern from our API Definition.

import typing

MllmVendor = typing.Union[
    typing.Literal["openai", "azure", "gemini", "vertexai", "xai", "qwen_omni", "openai_gpt_live"], typing.Any
]
