# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class RtzrAsrParams(UncheckedBaseModel):
    """
    RTZR ASR configuration parameters.
    """

    client_id: str = pydantic.Field()
    """
    RTZR client ID.
    """

    client_secret: str = pydantic.Field()
    """
    RTZR client secret.
    """

    api_base: typing.Optional[str] = pydantic.Field(default=None)
    """
    RTZR API base URL.
    """

    model_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    RTZR recognition model name.
    """

    language: typing.Optional[str] = pydantic.Field(default=None)
    """
    RTZR recognition language code. Defaults to Korean (`ko`).
    """

    sample_rate: typing.Optional[int] = pydantic.Field(default=None)
    """
    Input audio sample rate in Hz.
    """

    encoding: typing.Optional[str] = pydantic.Field(default=None)
    """
    Input audio encoding.
    """

    use_itn: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether to enable inverse text normalization.
    """

    use_disfluency_filter: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether to filter disfluencies such as stuttering.
    """

    use_profanity_filter: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether to filter profanity.
    """

    use_punctuation: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether to add punctuation to the recognized text.
    """

    keywords: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Keywords to improve recognition accuracy.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
