# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .sarvam_tts_params_target_language_code import SarvamTtsParamsTargetLanguageCode


class SarvamTtsParams(UncheckedBaseModel):
    """
    Sarvam TTS configuration parameters.
    """

    api_subscription_key: str = pydantic.Field()
    """
    Sarvam API subscription key
    """

    speaker: str = pydantic.Field()
    """
    Speaker voice to use.
    """

    target_language_code: SarvamTtsParamsTargetLanguageCode = pydantic.Field()
    """
    Target language code in BCP-47 format (e.g., `hi-IN`, `bn-IN`, `en-IN`).
    """

    pitch: typing.Optional[float] = pydantic.Field(default=None)
    """
    Pitch control for the `bulbul:v2` model.
    """

    pace: typing.Optional[float] = pydantic.Field(default=None)
    """
    Speech speed. Defaults to `1.0`.
    """

    loudness: typing.Optional[float] = pydantic.Field(default=None)
    """
    Audio loudness control for the `bulbul:v2` model.
    """

    speech_sample_rate: typing.Optional[int] = pydantic.Field(default=None)
    """
    Output speech sample rate in Hz. Defaults to `24000`.
    """

    enable_preprocessing: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether to normalize English words and numeric entities. Defaults to `false`.
    """

    model: typing.Optional[str] = pydantic.Field(default=None)
    """
    TTS model to use. Defaults to `bulbul:v3`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
