# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class SmallestAiAsrParams(UncheckedBaseModel):
    """
    Smallest AI ASR configuration parameters.
    """

    language: typing.Optional[str] = pydantic.Field(default=None)
    """
    Language code for speech recognition. This takes precedence over the top-level `asr.language` value.
    """

    url: typing.Optional[str] = pydantic.Field(default=None)
    """
    WebSocket endpoint for the Smallest AI streaming STT API.
    """

    api_key: str = pydantic.Field()
    """
    Smallest AI API key.
    """

    sample_rate: typing.Optional[int] = pydantic.Field(default=None)
    """
    Input audio sample rate in Hz.
    """

    encoding: typing.Optional[str] = pydantic.Field(default=None)
    """
    Input audio encoding.
    """

    word_timestamps: typing.Optional[str] = pydantic.Field(default=None)
    """
    Whether to include word-level timestamps.
    """

    sentence_timestamps: typing.Optional[str] = pydantic.Field(default=None)
    """
    Whether to include sentence-level timestamps.
    """

    diarize: typing.Optional[str] = pydantic.Field(default=None)
    """
    Whether to enable speaker diarization.
    """

    vad_events: typing.Optional[str] = pydantic.Field(default=None)
    """
    Whether to return voice activity detection events.
    """

    endpointing: typing.Optional[str] = pydantic.Field(default=None)
    """
    Whether to enable endpoint detection.
    """

    eou_timeout_ms: typing.Optional[int] = pydantic.Field(default=None)
    """
    End-of-utterance timeout in milliseconds.
    """

    format: typing.Optional[str] = pydantic.Field(default=None)
    """
    Whether to format the transcript.
    """

    finalize_on_words: typing.Optional[str] = pydantic.Field(default=None)
    """
    Whether to finalize results based on recognized words.
    """

    max_words: typing.Optional[str] = pydantic.Field(default=None)
    """
    Maximum number of words per result.
    """

    punctuate: typing.Optional[str] = pydantic.Field(default=None)
    """
    Whether to add punctuation.
    """

    capitalize: typing.Optional[str] = pydantic.Field(default=None)
    """
    Whether to capitalize transcript text.
    """

    itn_normalize: typing.Optional[str] = pydantic.Field(default=None)
    """
    Whether to enable inverse text normalization.
    """

    full_transcript: typing.Optional[str] = pydantic.Field(default=None)
    """
    Whether to return the full transcript.
    """

    keywords: typing.Optional[str] = pydantic.Field(default=None)
    """
    Comma-separated keyword boosts in `keyword:weight` format.
    """

    redact_pii: typing.Optional[str] = pydantic.Field(default=None)
    """
    Whether to redact personally identifiable information.
    """

    redact_pci: typing.Optional[str] = pydantic.Field(default=None)
    """
    Whether to redact payment card information.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
