# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .smallest_ai_asr_params import SmallestAiAsrParams


class SmallestAiAsr(UncheckedBaseModel):
    """
    Smallest AI ASR configuration.
    """

    language: typing.Optional[str] = pydantic.Field(default=None)
    """
    Language code for speech recognition.
    """

    params: SmallestAiAsrParams

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
