# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class SmallestAiTtsParams(UncheckedBaseModel):
    """
    Smallest AI TTS configuration parameters.
    """

    url: typing.Optional[str] = pydantic.Field(default=None)
    """
    HTTP endpoint for the Smallest AI streaming TTS API.
    """

    api_key: str = pydantic.Field()
    """
    Smallest AI API key.
    """

    model: typing.Optional[str] = pydantic.Field(default=None)
    """
    Smallest AI TTS model name.
    """

    voice_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Smallest AI voice identifier.
    """

    sample_rate: typing.Optional[int] = pydantic.Field(default=None)
    """
    Output audio sample rate in Hz.
    """

    speed: typing.Optional[float] = pydantic.Field(default=None)
    """
    Speech rate multiplier.
    """

    language: typing.Optional[str] = pydantic.Field(default=None)
    """
    Language code for speech synthesis.
    """

    number_pronunciation_language: typing.Optional[str] = pydantic.Field(default=None)
    """
    Language used to pronounce numbers.
    """

    math_notation: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether to verbalize mathematical notation.
    """

    pronunciation_dicts: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Pronunciation dictionaries applied during synthesis.
    """

    session_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Client-provided session identifier.
    """

    request_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Client-provided request identifier.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
